### ISSUE TITLE
Merging our efforts

### ISSUE THREAD

**Issue by 197g** [aidarbiktimirov/tfp#1]
I have recently delved into the same topic as this project and written some eerily similar thing on my own
https://github.com/HeroicKatora/Functional-Cpp-Templates

My own contributions to the topic are specifically using c++17 features to, for example, allow converting all the typename templates in the c++ standard to functions inside functional template language, providing a way for matching, and Lambda-like function definitions.

Now I do not know whether or not you are still interested, but I would really enjoy seeing you join the effort :)

If you want to, please join the Discord server https://discord.gg/jAyP79x

добры день

**Comment by aydarbiktimirov** [comment]
Hi @HeroicKatora, this was just my university project and I don't think I have time to work on it now, sorry.

**Comment by 197g** [comment]
No worries or hard feelings :)

**Comment by 197g** [comment]
I do have to inquire about your license though, can I freely use your code, for example your brainfuck implementation?

**Comment by aydarbiktimirov** [comment]
Sure thing – do whatever you want with it :)
